spring.application.name=grpc-metrics

# Porta do servidor gRPC
grpc.server.port=9090

# Porta do servidor REST (para o dashboard depois)
server.port=8080

# Desativa o banner desnecessário
spring.main.banner-mode=off

# Log mais limpo
logging.level.root=WARN
logging.level.com.example.grpc_metrics=INFO
logging.level.net.devh.boot.grpc=INFO